CREATE TABLE ces_patients (
patient_id int, 
emr_id varchar(30),
reg_location varchar(30),
reg_date date,
dob date,
age_in_years int,
gender char(1),
state varchar(50),
municipilty varchar(50),
migrant bit,
Indigenous bit,
Disability bit,
education bit,
active_case_finding bit,
civil_status varchar(50),
occupation varchar(50),
dead bit,
date_of_death date,
cause_of_Death varchar(50),
PHD_GAD_Score bit,
PHD_GAD_DATE date,
recent_height float,
recent_weight float,
recent_bmi float,
last_enc_date date,
last_enc_type varchar(50)
);