CREATE TABLE encuentro_signos_vitales
(
    emr_id          	VARCHAR(25),
    encounter_id		int,
    encounter_location	varchar(255),
    encounter_datetime	datetime,
    encounter_provider 	VARCHAR(255),
    date_entered		datetime,
    user_entered		varchar(255),
    height				float,
    weight				float,
    bmi 				float,
    systolic_bp			int,
    diastolic_bp		int,
    o2_saturation		float,
    fasting 			bit,
    glucose 			float,
    temperature			float,
    heart_rate			float,
    respiratory_rate	float,
    phq2				int,
    gad2				int,
    chief_complaint		text,
    index_asc			int,
    index_desc			int
);