CREATE TABLE medicamentos_staging
(
 person_uuid                    char(38),      
 emr_id                         varchar(50),   
 encuentro_id                   varchar(50),  
 encounter_uuid                 char(38),     
 encuentro_fecha                datetime,     
 emr_instancia                  varchar(255), 
 medicamento_nombre             varchar(255),
 frascos_cajas                  float,
 duración                       float,         
 duración_unidad                varchar(255),  
 instrucciones                  text,          
 dosis1_dosis                   float,         
 dosis1_dosis_unidad            varchar(255),  
 dosis1_mañana                  bit,           
 dosis1_mañana_instrucciones    varchar(255),  
 dosis1_medio_dia               bit,           
 dosis1_medio_dia_instrucciones varchar(255),  
 dosis1_tarde                   bit,           
 dosis1_tarde_instrucciones     varchar(255),  
 dosis1_noche                   bit,           
 dosis1_noche_instrucciones     varchar(255),  
 dosis2_dosis                   float,         
 dosis2_dosis_unidad            varchar(255),  
 dosis2_mañana                  bit,           
 dosis2_mañana_instrucciones    varchar(255),  
 dosis2_medio_dia               bit,           
 dosis2_medio_dia_instrucciones varchar(255),  
 dosis2_tarde                   bit,           
 dosis2_tarde_instrucciones     varchar(255),  
 dosis2_noche                   bit,           
 dosis2_noche_instrucciones     varchar(255),
 index_asc                      int,
 index_desc                     int
);
